apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworldapp
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
        - name: tomcat
          image: abdulsukku/abd-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: helloworldapp
